alias cal='cal -m'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias l='ls -alFh --color=auto'
alias vlock='vlock -a'
alias kismet_client='kismet_client -q'
alias wodim='wodim -v'
alias ssh='ssh -Y'
alias tmux='tmux -2'
